In [11]:
from numpy import select
import pandas as pd
import duckdb
pd.set_option('display.max_columns', None)

chemin_fichier = r"retailcorps.parquet"

df=duckdb.query(f"""
    select *
    From read_parquet('{chemin_fichier}')
""").df()

In [12]:
display(df.tail(10))

,OrderLineID,Invoice,StockCode,Description,Quantity,InvoiceDate,CustomerID,Country,ProductCategoryCode,ProductCategory,ProductFamily,ProductNameClean,UnitPriceGBP,UnitCostGBP,CustomerSegment,CustomerType,LoyaltyProgram,SalesChannel,PaymentMethod,WarehouseID,PromotionCode,DiscountRate,OrderStatus,DeliveryTime,Continent,Region,Currency
1072697,1016248,578065,22807,SET OF 6 T-LIGHTS TOADSTOOLS,1,2011-11-22 15:41:00,NaN,United Kingdom,HOME,Home decoration,Interior,Set Of 6 T-Lights Toadstools,14.26,6.66,VIP,Retailer,Gold,Phone,Invoice,WH-UK-02,NONE,0.0,Completed,15,Europe,Western Europe,GBP
1072698,1045002,580152,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-02 10:22:00,12364.0,Belgium,OTHER,Other,Other,Pack Of 20 Spaceboy Napkins,4.75,2.99,Low value,Retailer,No,Online,Card,WH-EU-01,XMAS,0.15,Completed,15,Europe,Western Europe,EUR
1072699,1064326,581419,23292,SPACEBOY CHILDRENS CUP,8,2011-12-08 15:03:00,15484.0,United Kingdom,CHILD,Children,Occasions,Spaceboy Childrens Cup,19.47,8.21,Regular,Retailer,Bronze,Store,Bank transfer,WH-UK-01,CLEARANCE,0.2,Completed,6,Europe,Western Europe,GBP
1072700,1039727,579690,22734,SET OF 6 RIBBONS VINTAGE CHRISTMAS,2,2011-11-30 14:03:00,15060.0,United Kingdom,SEASONAL,Seasonal,Occasions,Set Of 6 Ribbons Vintage Christmas,13.11,6.0,Loyal,Small business,Silver,Store,Bank transfer,WH-UK-01,XMAS,0.15,Completed,1,Europe,Western Europe,GBP
1072701,1038571,579535,20668,DISCO BALL CHRISTMAS DECORATION,24,2011-11-30 09:50:00,15414.0,United Kingdom,SEASONAL,Seasonal,Occasions,Disco Ball Christmas Decoration,36.09,19.76,Loyal,Retailer,Silver,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Cancelled,2,Europe,Western Europe,GBP
1072702,1033960,579196,21070,VINTAGE BILLBOARD MUG,1,2011-11-28 15:54:00,14096.0,United Kingdom,KITCHEN,Kitchenware,Interior,Vintage Billboard Mug,29.53,14.3,VIP,Retailer,Gold,Phone,Invoice,WH-UK-02,WELCOME10,0.1,Cancelled,10,Europe,Western Europe,GBP
1072703,1062960,581310,16238,PARTY TIME PENCIL ERASERS,1,2011-12-08 11:43:00,16442.0,United Kingdom,STATIONERY,Stationery,Office,Party Time Pencil Erasers,1.84,0.63,VIP,Small business,Gold,Store,Bank transfer,WH-UK-01,NONE,0.0,Completed,8,Europe,Western Europe,GBP
1072704,1033416,579188,22139,RETROSPOT TEA SET CERAMIC 11 PC,4,2011-11-28 15:34:00,12748.0,United Kingdom,KITCHEN,Kitchenware,Interior,Retrospot Tea Set Ceramic 11 Pc,28.42,13.91,Low value,Retailer,No,Phone,Invoice,WH-UK-02,WELCOME10,0.1,Completed,15,Europe,Western Europe,GBP
1072705,1001514,576932,22086,PAPER CHAIN KIT 50'S CHRISTMAS,5,2011-11-17 11:12:00,15443.0,United Kingdom,SEASONAL,Seasonal,Occasions,Paper Chain Kit 50'S Christmas,10.57,3.06,Regular,Individual,Bronze,Marketplace,PayPal,WH-UK-02,NONE,0.0,Completed,9,Europe,Western Europe,GBP
1072706,1035637,579432,85203,HANGING WOOD AND FELT BUTTERFLY,8,2011-11-29 13:12:00,15311.0,United Kingdom,OTHER,Other,Other,Hanging Wood And Felt Butterfly,12.11,5.37,VIP,Retailer,Gold,Online,Card,WH-UK-01,XMAS,0.15,Completed,11,Europe,Western Europe,GBP

In [13]:
def explorer_dataset(dataset):
        print(f"Start {'-'*10} Pour ce dataset, la taille est de {dataset.shape} {'-'*10}")
        print('-'*30)
        display(dataset.head(3))
        print('-'*30)
        display(dataset.tail(3))
        print('-'*30)
        print(f"Présences de valeurs 'NaN'.")
        print(f"{dataset.isna().sum()}")
        display(dataset[dataset.isna().any(axis=1)])
        print('-'*30)
        print(f"Les doublons")
        print(f"{dataset.duplicated().sum()}")
        print('-'*30)
        print(f"Les types de données")
        print(f"{dataset.dtypes}")
        print('-'*30)
        print(f"Description")
        display(dataset.describe().T)
        print("FIN"+'-'*100)

In [ ]:
explorer_dataset(df)

Start ---------- Pour ce dataset, la taille est de (1072707, 27) ----------
------------------------------

,OrderLineID,Invoice,StockCode,Description,Quantity,InvoiceDate,CustomerID,Country,ProductCategoryCode,ProductCategory,ProductFamily,ProductNameClean,UnitPriceGBP,UnitCostGBP,CustomerSegment,CustomerType,LoyaltyProgram,SalesChannel,PaymentMethod,WarehouseID,PromotionCode,DiscountRate,OrderStatus,DeliveryTime,Continent,Region,Currency
0,1,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,13085.0,United Kingdom,SEASONAL,Seasonal,Occasions,15Cm Christmas Glass Ball 20 Lights,17.82,8.47,Regular,Small business,Bronze,Online,Card,WH-UK-01,NONE,0.0,Completed,11,Europe,Western Europe,GBP
1,2,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,13085.0,United Kingdom,HOME,Home decoration,Interior,Pink Cherry Lights,21.29,11.43,Regular,Small business,Bronze,Online,Card,WH-UK-01,NONE,0.0,Completed,11,Europe,Western Europe,GBP
2,3,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,13085.0,United Kingdom,HOME,Home decoration,Interior,White Cherry Lights,7.2,2.6,Regular,Small business,Bronze,Online,Card,WH-UK-01,NONE,0.0,Completed,11,Europe,Western Europe,GBP

------------------------------

,OrderLineID,Invoice,StockCode,Description,Quantity,InvoiceDate,CustomerID,Country,ProductCategoryCode,ProductCategory,ProductFamily,ProductNameClean,UnitPriceGBP,UnitCostGBP,CustomerSegment,CustomerType,LoyaltyProgram,SalesChannel,PaymentMethod,WarehouseID,PromotionCode,DiscountRate,OrderStatus,DeliveryTime,Continent,Region,Currency
1072704,1033416,579188,22139,RETROSPOT TEA SET CERAMIC 11 PC,4,2011-11-28 15:34:00,12748.0,United Kingdom,KITCHEN,Kitchenware,Interior,Retrospot Tea Set Ceramic 11 Pc,28.42,13.91,Low value,Retailer,No,Phone,Invoice,WH-UK-02,WELCOME10,0.1,Completed,15,Europe,Western Europe,GBP
1072705,1001514,576932,22086,PAPER CHAIN KIT 50'S CHRISTMAS,5,2011-11-17 11:12:00,15443.0,United Kingdom,SEASONAL,Seasonal,Occasions,Paper Chain Kit 50'S Christmas,10.57,3.06,Regular,Individual,Bronze,Marketplace,PayPal,WH-UK-02,NONE,0.0,Completed,9,Europe,Western Europe,GBP
1072706,1035637,579432,85203,HANGING WOOD AND FELT BUTTERFLY,8,2011-11-29 13:12:00,15311.0,United Kingdom,OTHER,Other,Other,Hanging Wood And Felt Butterfly,12.11,5.37,VIP,Retailer,Gold,Online,Card,WH-UK-01,XMAS,0.15,Completed,11,Europe,Western Europe,GBP

------------------------------
Présences de valeurs 'NaN'.
OrderLineID                 0
Invoice                     0
StockCode                   0
Description             12993
Quantity                    0
InvoiceDate                 0
CustomerID             254201
Country                     0
ProductCategoryCode      3226
ProductCategory          4342
ProductFamily               0
ProductNameClean         4405
UnitPriceGBP                0
UnitCostGBP              1044
CustomerSegment             0
CustomerType                0
LoyaltyProgram              0
SalesChannel             4195
PaymentMethod               0
WarehouseID              1775
PromotionCode            1777
DiscountRate              636
OrderStatus              1334
DeliveryTime              815
Continent                   0
Region                      0
Currency                 1673
dtype: int64

,OrderLineID,Invoice,StockCode,Description,Quantity,InvoiceDate,CustomerID,Country,ProductCategoryCode,ProductCategory,ProductFamily,ProductNameClean,UnitPriceGBP,UnitCostGBP,CustomerSegment,CustomerType,LoyaltyProgram,SalesChannel,PaymentMethod,WarehouseID,PromotionCode,DiscountRate,OrderStatus,DeliveryTime,Continent,Region,Currency
31,32,489437,22143,CHRISTMAS CRAFT HEART DECORATIONS,6,2009-12-01 09:08:00,NaN,United Kingdom,SEASONAL,Seasonal,Occasions,Christmas Craft Heart Decorations,11.81,6.12,Regular,Retailer,Bronze,Marketplace,PayPal,WH-UK-02,CLEARANCE,0.2,Completed,15,Europe,Western Europe,GBP
45,46,489437,21989,PACK OF 20 SKULL PAPER NAPKINS,12,2009-12-01 09:08:00,15362.0,United Kingdom,STATIONERY,NaN,Office,Pack Of 20 Skull Paper Napkins,1.85,0.64,Regular,Retailer,Bronze,Marketplace,PayPal,WH-UK-02,CLEARANCE,0.2,Completed,15,Europe,Western Europe,GBP
120,121,489443,21035,SET/2 RED SPOTTY TEA TOWELS,12,2009-12-01 09:50:00,NaN,United Kingdom,KITCHEN,Kitchenware,Interior,Set/2 Red Spotty Tea Towels,34.49,18.32,Loyal,Individual,Silver,Phone,Invoice,WH-UK-02,WELCOME10,0.1,Completed,2,Europe,Western Europe,GBP
126,127,489444,POST,POSTAGE,1,2009-12-01 09:55:00,12636.0,USA,OTHER,Other,Other,Postage,1.13,0.54,Low value,Individual,No,NaN,Card,WH-NA-01,WELCOME10,0.1,Completed,4,North America,North America,USD
146,147,489446,21733,RED HANGING HEART T-LIGHT HOLDER,32,2009-12-01 10:06:00,13758.0,United Kingdom,HOME,NaN,Interior,Red Hanging Heart T-Light Holder,0,2.4,Low value,Individual,No,Online,Card,WH-UK-01,NONE,0.0,Completed,11,Europe,Western Europe,GBP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1072684,1034618,579297,21191,LARGE WHITE HONEYCOMB PAPER BELL,4,2011-11-29 11:23:00,NaN,United Kingdom,STATIONERY,Stationery,Office,Large White Honeycomb Paper Bell,4.31,1.57,VIP,Retailer,Gold,Marketplace,PayPal,WH-UK-02,NONE,0.0,Completed,14,Europe,Western Europe,GBP
1072693,1046889,580366,23393,HOME SWEET HOME CUSHION COVER,2,2011-12-02 16:38:00,NaN,United Kingdom,OTHER,Other,Other,Home Sweet Home Cushion Cover,5.02,2.04,VIP,Retailer,Gold,Marketplace,PayPal,WH-UK-02,XMAS,0.15,Completed,12,Europe,Western Europe,GBP
1072695,1040396,579751,22697,GREEN REGENCY TEACUP AND SAUCER,4,2011-11-30 14:46:00,NaN,United Kingdom,KITCHEN,Kitchenware,Interior,Green Regency Teacup And Saucer,30.23,18.27,VIP,Retailer,Gold,Marketplace,PayPal,WH-UK-02,WELCOME10,0.1,Completed,9,Europe,Western Europe,GBP
1072696,1039841,579694,21165,BEWARE OF THE CAT METAL SIGN,2,2011-11-30 14:11:00,NaN,United Kingdom,HOME,Home decoration,Interior,Beware Of The Cat Metal Sign,"13,12",5.47,VIP,Retailer,Gold,Store,Bank transfer,WH-UK-01,SPRING,0.05,Completed,15,Europe,Western Europe,GBP
1072697,1016248,578065,22807,SET OF 6 T-LIGHTS TOADSTOOLS,1,2011-11-22 15:41:00,NaN,United Kingdom,HOME,Home decoration,Interior,Set Of 6 T-Lights Toadstools,14.26,6.66,VIP,Retailer,Gold,Phone,Invoice,WH-UK-02,NONE,0.0,Completed,15,Europe,Western Europe,GBP

------------------------------
Les doublons